main: org.thespherret.plugins.duelpvp.org.thespherret.plugins.koth.Main
name: DuelPVP
version: 1.0
author: Spherret.
description: DuelPVP.
commands:
  duel:
  accept:
  deny:
  arenas:
  create:
  duelpvp:
  end:
  arenatp:
  lobbytp:
  forcestart:
  arenatoggle:
  selectkit:
permissions:
  DuelPVP.Admin:
    default: op
    description: Allows players to create arenas.
  DuelPVP.Force:
    default: op
    description: Allows force starting arena matches.
  DuelPVP.SelectArena:
    default: op
    description: Allows force starting arena matches.