main: org.thespherret.plugins.duelpvp.Main
name: DuelPVP
version: 1.0
author: Spherret.
description: DuelPVP.
commands:
 duel:
 arenas:
 create:
 duelpvp:
 end:
 arenatp:
permissions:
  DuelPvP.admin:
    default: op
    description: Allows players to create arenas.