main: org.thespherret.plugins.duelpvp.Main
name: DuelPVP
version: 1.0
author: Spherret.
description: DuelPVP.
commands:
 duel:
 accept:
 deny:
 arenas:
 create:
 duelpvp:
 end:
 arenatp:
 lobbytp:
 forcestart:
 arenatoggle:
permissions:
  DuelPvP.admin:
    default: op
    description: Allows players to create arenas.
  DuelPvP.force:
    default: op
    description: Allows force starting arena matches.